name: Daily News Scraper

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 불러오기
        uses: actions/checkout@v4

      - name: Python 환경 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 필요 패키지 설치
        run: |
          pip install -r requirements.txt

      - name: 스크래핑 코드 실행
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py
